---

- name: remove aether 5gc
  kubernetes.core.helm:
    name: sd-core
    release_namespace: omec
    state: absent
    wait: true
  when: inventory_hostname in groups['master_nodes']
  ignore_errors: yes

- name: remove rancher chart repo
  kubernetes.core.helm_repository:
    name: rancher
    state: absent
    repo_url: "http://charts.rancher.io/"
  when: inventory_hostname in groups['master_nodes']
  ignore_errors: yes

- name: remove aether chart repo
  kubernetes.core.helm_repository:
    name: aether
    state: absent
    repo_url: "https://charts.aetherproject.org"
  when: inventory_hostname in groups['master_nodes']
  ignore_errors: yes

- name: remove onosproject chart repo
  kubernetes.core.helm_repository:
    name: onosproject
    state: absent
    repo_url: "https://charts.onosproject.org"
  when: inventory_hostname in groups['master_nodes']
  ignore_errors: yes

- name: remove atomix chart repo
  kubernetes.core.helm_repository:
    name: atomix
    state: absent
    repo_url: "https://charts.atomix.io"
  when: inventory_hostname in groups['master_nodes']
  ignore_errors: yes

- name: remove cord chart repo
  kubernetes.core.helm_repository:
    name: cord
    state: absent
    repo_url: "https://charts.opencord.org"
  when: inventory_hostname in groups['master_nodes']
  ignore_errors: yes

- name: waiting for aether pods to terminate
  shell: |
    kubectl wait -n omec --for=delete --all=true -l app!=ue pod --timeout=180s
  when: inventory_hostname in groups['master_nodes']
  ignore_errors: yes

- name: delete namespace omec
  shell: |
    kubectl delete namespace omec
  when: inventory_hostname in groups['master_nodes']
  ignore_errors: yes
  